---
params:
  rd: !r data.frame(a = 1:3) # plotting data
  ip: ! list(a = 1:5) # input list
title: "Benchmark report"
fig_height: 2.6
fig_width: 4
output: pdf_document
---

```{r setup, include=FALSE}
# output: 
#   pdf_document:
#     latex_engine: xelatex
#     template: pdf/layout.tex
#     includes:
#       in_header: pdf/preamble.sty
library(knitr)# Basic knitr options
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = F,
               fig.height = 6)
knit_engines$set(asis = function(options) {
  if (options$echo && options$eval) knit_child(text = options$code)
})

# Specify paramaters
for (i in 1:length(params)){
  assign(names(params)[i],
         params[[i]],
         env = .GlobalEnv)
}


library(radarchart)
source('global.R')
```


## Radar charts

```{r}
chunks <- rep(NA, length(tab_names))
for (i in 1:length(tab_names)){
  tab_name <- tab_names[i]
  title <- simple_cap(gsub('_', ' ', tab_name))
  title <- convert_capitalization(title)
  chunks[i] <- paste0('### ', title, '\n\n```{r, fig.height = 6, fig.width = 7}\n',
         'make_radar_chart(rd, tn = "', tab_name, '", label_size = 14, height = 250, gg = TRUE)\n```\n\n')
}
```

```{r}
chunks <- paste0(chunks, collapse = '')

## Add raw data
ip <- reactiveValuesToList(ip)
ip <- unlist(ip)
df <- data.frame(key = names(ip),
                 value = ip)
df$key <- as.character(df$key)
df$combined_name <- substr(df$key, 1, nchar(df$key) - 9)
df <- left_join(df, competency_dict, by = 'combined_name') %>%
  dplyr::select(tab_name, competency, value)
names(df) <- c('Area', 'Competency', 'Score')
df$Area <- simple_cap(gsub('_', ' ', df$Area))
df$Area <- convert_capitalization(df$Area)
df$Competency <- simple_cap(gsub('_', ' ', df$Competency))
df$Competency <- convert_capitalization(df$Competency)

final_chunk <- paste0("### Raw data\n\n```{r}\nkable(df, row.names = FALSE)\n```\n"
  
)
chunks <- paste0(chunks, final_chunk, collapse = '')
```

```{r}
# Write our order / child-calls to a doc
file_connection <- file('children.Rmd')
writeLines(paste0('---\noutput: pdf_document\n---\n\n', 
                  chunks), 
           file_connection)
close(file_connection)
```

```{r child='children.Rmd', echo = FALSE}
# Now, we simply include "children.Rmd" to construct our doc
# (ie, children is the child doc, and each section is a grandchild)
```

```{r, results='hide'}
# Having already called the auto-generated children.Rmd, we can delete it
file.remove('children.Rmd')
```

