---
title: "Benchmark Report"
params:
  rd: !r data.frame(a = 1:3) # plotting data
  ip: ! list(a = 1:5) # input list
output:
  pdf_document: 
    pandoc_args: [
      "-V", "classoption=twocolumn"
    ]
  html_document: default
header-includes:
- \usepackage{lipsum}  # just used for producing example text in document
---
```{r setup, include=FALSE}
# output: 
#   pdf_document:
#     latex_engine: xelatex
#     template: pdf/layout.tex
#     includes:
#       in_header: pdf/preamble.sty
library(knitr)# Basic knitr options
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = F,
               fig.height = 6)
# knit_engines$set(asis = function(options) {
#   if (options$echo && options$eval) knit_child(text = options$code)
# })
```


```{r}
# Specify paramaters
for (i in 1:length(params)){
  assign(names(params)[i],
         params[[i]],
         env = .GlobalEnv)
}

# save(rd, file = 'rd.RData')
# save(ip, file = 'ip.RData')
# load('ip.RData')
# load('rd.RData')

library(radarchart)
source('../global.R', chdir = TRUE, echo = FALSE)

# Define function for getting all qualy text associated with any tab name
make_qualy_table <- function(data, tn = 'organization_and_governance'){
  # Get the qualitative comments
  sub_data <- data %>%
    filter(grepl(tn, key)) %>%
    filter(grepl('qualy', key)) %>%
    dplyr::rename(`Qualitative assessment` = value)
  # Clean up the keys
  sub_data <-
    sub_data %>%
    mutate(key = gsub('_qualy', '', key)) %>%
    mutate(key = convert_capitalization(simple_cap(gsub('_', ' ', key)))) %>%
    dplyr::rename(Dimension = key)
  return(kable(sub_data, type = 'latex'))
}

# Define function for getting all the text associated with any tab name (in text format, not table)
make_qualy_text <- function(data, tn = 'organization_and_governance'){
  # Get the qualitative comments
  sub_data <- data %>%
    filter(grepl(tn, key)) %>%
    filter(grepl('qualy', key)) %>%
    .$value
  sub_data <- sub_data[!is.na(sub_data) & sub_data != '']
  return(paste0(sub_data, collapse = '\n\n'))
}

```




```{r}
# Get raw data
ip <- reactiveValuesToList(ip)
ip <- unlist(ip)
df <- data.frame(key = names(ip),
                 value = ip)
df$key <- as.character(df$key)

chunks <- rep(NA, length(tab_names))
for (i in 1:length(tab_names)){
  tab_name <- tab_names[i]
  title <- simple_cap(gsub('_', ' ', tab_name))
  title <- convert_capitalization(title)
  title <- trimws(title, 'both')
  title <- as.character(title)
  chunks[i] <- paste0('\\section{', title, '}\n\n```{r}\n',
         'make_radar_chart(rd, tn = "', tab_name, '", label_size = 14, height = 250, gg = TRUE)\n```\n\n',
         '```{r, results = "asis"}\n',
         'cat(make_qualy_text(tn = "', tab_name, '",data = df))\n```\n\n\\onecolumn\n\n\\pagebreak\n\n\\twocolumn')
}
```


```{r}
# Write our order / child-calls to a doc
file_connection <- file('children.Rmd')
writeLines(paste0(#'---\noutput: pdf_document\n---\n\n', 
                  chunks), 
           file_connection)
close(file_connection)
```


```{r child='children.Rmd', echo = FALSE}
# Now, we simply include "children.Rmd" to construct our doc
# (ie, children is the child doc, and each section is a grandchild)
```

```{r, results='hide'}
# Having already called the auto-generated children.Rmd, we can delete it
file.remove('children.Rmd')

# Close the pool
tryCatch(pool::poolClose(pool), error = function(e) {message('')})

```




Fin.
